name: ridelink
description: A collaborative cab-sharing mobile application built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  firebase_crashlytics: ^4.1.3
  
  # Google Services
  google_sign_in: ^6.2.0
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_polyline_algorithm: ^3.1.0
  maps_toolkit: ^2.0.1
  
  # Free Map Services
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  cached_network_image: ^3.3.0
  
  # State Management
  provider: ^6.1.2
  
  # UI & Navigation
  go_router: ^14.6.1
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # HTTP & Networking
  http: ^1.1.2
  connectivity_plus: ^6.0.5
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  image_picker: ^1.0.4
  
  # Payment
  flutter_stripe: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/